### ISSUE TITLE
Permission denied activating e3sm_unified on perlmutter

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/e3sm-unified#117]
source /global/common/software/e3sm/anaconda_envs/load_latest_e3sm_unified_pm-cpu.sh get the following error mess

`PermissionError: [Errno 13] Permission denied: '/global/common/software/e3sm/anaconda_envs/base/lib/python3.8/site-packages/idna/__init__.py'`

```
wlin@perlmutter:login16:~> ls -l /global/common/software/e3sm/anaconda_envs/base/lib/python3.8/site-packages/boltons/__init__.py
-rw-rw---- 2 xylar xylar 0 Mar 31 18:55 /global/common/software/e3sm/anaconda_envs/base/lib/python3.8/site-packages/boltons/__init__.py
```

**Comment by xylar** [comment]
This is a temporary issue while I install a new E3SM-Unified.  It will be fixed in the next hour or 2 as the installation finishes.

**Comment by xylar** [comment]
Okay, should be fixed now.

**Comment by wlin7** [comment]
Thanks @xylar . Works well now.

**Comment by xylar** [comment]
Great, glad to hear it!
