### ISSUE TITLE
How to use e3sm after activating through conda

### ISSUE THREAD

**Issue by ssk351** [E3SM-Project/e3sm-unified#121]
I have installed e3sm using conda ( **conda create -n e3sm-unified -c conda-forge -c e3sm e3sm-unified**). 
Activated using conda activate e3sm-unifed..
After that, I am not getting how to start running model...Checked /home/ssk/software/anaconda3/envs/e3sm-unified
it contains directories (like bin,cmake,include etc... **attahced)**
About the machine:
HPC : OS: 
![Screenshot 2024-07-25 171739](https://github.com/user-attachments/assets/4b60ed43-190f-4c29-9cc2-0124e542b9c3)
centos
Could you please suggest the possible way.

**Comment by xylar** [comment]
@ssk351, E3SM-Unified provides preprocessing and analysis software to use in conjunction with E3SM simulations.  There is not currently a way to install E3SM inself from a conda package, nor is there any plan to create one.

**Comment by ssk351** [comment]
I have found this links..
https://e3sm.org/e3sm-unified-1-10-0/
https://e3sm.org/resources/tools/other-tools/e3sm-unified-environment/
If these were not for proper e3sm model installation..
Could you please any document to install the same in the hpc system.
It would be vary help full for me..

**Comment by xylar** [comment]
I will also mention that it is my sense that getting E3SM to build on a new HPC system is not very easy, just to make sure you're prepared for the level of effort that may be involved.

**Comment by xylar** [comment]
I'm going to close this issue for now, since it sounds like your needs are not for E3SM-Unified but for E3SM itself.  But feel free to comment here if you need to.

**Comment by ssk351** [comment]
Yes,
Thank you
