### ISSUE TITLE
Updates planned for 1.2.1

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm-unified#14]
NCO 4.7.5

**Comment by xylar** [comment]
@zshaheen, @doutriaux1 and @sterlingbaldwin, could you let me know what updates you'd like to see for v1.2.1?  I'll try to get it going tomorrow.

**Comment by xylar** [comment]
mpas_analysis v1.0

**Comment by zshaheen** [comment]
@xylar I'm releasing v1.3.4 of e3sm_diags sometime this week. When do you plan on releasing v1.2.1 of e3sm-unified?

**Comment by xylar** [comment]
@zshaheen, no rush, I just had the sense that it's about time.  We'll be releasing MPAS-Analysis v1.0 sometime in the next few days.

**Comment by zshaheen** [comment]
I guess I'll wait to include any new e3sm_diags in another version of the unified env. Everyone on the team is gone, and I'd like another person to test before we release. So for this release, I don't have anything new.

**Comment by xylar** [comment]
@zshaheen, I think I might hold off on 1.2.1 for now.  If there are only 2 updated packages, that doesn't seem worth the effort to deploy on all machines.  Keep me posted on the next release of e3sm_diags.

**Comment by sterlingbaldwin** [comment]
@xylar Im getting closer to the processflow 2.0 release (1-2 weeks). I'll let you know once its ready.

**Comment by xylar** [comment]
Okay, that also sounds good.  So it definitely sounds like I should wait.

**Comment by xylar** [comment]
Addressed by #16
