### ISSUE TITLE
Packages needed to support MPAS COMPASS workflow

### ISSUE THREAD

**Issue by pwolfram** [E3SM-Project/e3sm-unified#25]
Following the PR at https://github.com/MPAS-Dev/MPAS-Model/pull/74, we need the following python packages needed to support use of JIGSAW in COMPASS include:

 * pyflann 1.9.1 (`conda install -c conda-forge pyflann`)
 * skimage 0.14.0 (`conda install -c conda-forge scikit-image`)

cc @sbrus89 and @mark-petersen 

Note, this is not high-priority issue because only the users on this issue are affected for the short term (e.g., to Nov 2018).

**Comment by pwolfram** [comment]
@xylar, latest is best, especially if that is the easiest.  I am not aware of any reason to tie to version for now.  @sbrus89, do we need these tied to a particular version number?

**Comment by sbrus89** [comment]
@xylar, I agree with @pwolfram. The latest versions are best. Thanks!

**Comment by xylar** [comment]
Addressed in #26
