### ISSUE TITLE
Library link problems on new conda install

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/e3sm-unified#37]
In a fresh conda install, I am getting link errors when trying to run NCO tools:
```
ncks: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
It looks like `openssl` is installed, but maybe `ncks` was built with a different version? Commands to install e3sm-unified:
```
conda create --name e3sm-unified python=2.7
conda activate e3sm-unified
conda install -c conda-forge -c e3sm -c cdat e3sm-unified mesalib
```

**Comment by tangq** [comment]
I got the same errors on a Mac installation via Miniconda yesterday.

**Comment by brhillman** [comment]
Thanks for confirming @tangq. I should also point out that I was using Miniconda on a Linux cluster.

**Comment by czender** [comment]
Pinging @xylar who might confirm whether he can reproduce the issue and whether we need to re-pin the conda NCO package to a different SSL version.

**Comment by czender** [comment]
@tangq and @brhillman please post the results of `ncremap --config` so we can verify you are using the Conda NCO with the Conda SSL.

**Comment by brhillman** [comment]
```
(e3sm-unified) [bhillma@chama-login2 ~]$ ncremap --config
ESMF_RegridWeightGen: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
/ascldap/users/bhillma/software/miniconda3/envs/e3sm-unified/bin/ncremap: line 695: [: : integer expression expected
ncremap, the NCO regridder and map- and grid-generator, version 
Copyright (C) 2016--2018 Charlie Zender
This program is part of NCO, the netCDF Operators
NCO is free software and comes with a BIG FAT KISS and ABSOLUTELY NO WARRANTY
You may redistribute and/or modify NCO under the terms of the
GNU General Public License (GPL) Version 3 with exceptions described in the LICENSE file
GPL: http://www.gnu.org/copyleft/gpl.html
LICENSE: https://github.com/nco/nco/tree/master/LICENSE
Config: ncremap running from directory /home/bhillma/software/miniconda3/envs/e3sm-unified/bin
Config: Calling NCO binaries in directory /home/bhillma/software/miniconda3/envs/e3sm-unified/bin
Config: Binaries linked to netCDF library version libraries:
Config: No hardcoded path/module overrides
Config: ESMF weight-generation command ESMF_RegridWeightGen version  found as /ascldap/users/bhillma/software/miniconda3/envs/e3sm-unified/bin/ESMF_RegridWeightGen
Config: Tempest weight-generation command GenerateOfflineMap not found
```

**Comment by tangq** [comment]
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib

  Referenced from: /Users/ginger/miniconda3/lib/libssh2.1.dylib

  Reason: image not found

/Users/ginger/miniconda3/bin/ncremap: line 695: [: : integer expression expected

ncremap, the NCO regridder and map- and grid-generator, version 

Copyright (C) 2016--2018 Charlie Zender

This program is part of NCO, the netCDF Operators

NCO is free software and comes with a BIG FAT KISS and ABSOLUTELY NO WARRANTY

You may redistribute and/or modify NCO under the terms of the

GNU General Public License (GPL) Version 3 with exceptions described in the LICENSE file

GPL: http://www.gnu.org/copyleft/gpl.html

LICENSE: https://github.com/nco/nco/tree/master/LICENSE

Config: ncremap running from directory /Users/ginger/miniconda3/bin

Config: Calling NCO binaries in directory /Users/ginger/miniconda3/bin

Config: Binaries linked to netCDF library version 

Config: No hardcoded path/module overrides

Config: ESMF weight-generation command ESMF_RegridWeightGen version  found as /Users/ginger/miniconda3/bin/ESMF_RegridWeightGen

Config: Tempest weight-generation command GenerateOfflineMap not found

**Comment by czender** [comment]
I can verify that these are dynamic linking errors and not NCO errors per se. Until Xylar has a chance to look, your best options are 1) install an older E3SM_Unified that might work or 2) Install NCO on its own (conda install nco) and do not run in the E3SM_Unified environment or 3) run the NCO in my home directories at DOE centers (in ~/zender/[bin/lib]).

**Comment by tangq** [comment]
In my case, it is a conda install nco. But it is still problematic.

**Comment by xylar** [comment]
@brhillman, @tangq and @czender, I'm suspicious that this isn't a problem to do with e3sm-unified.  I haven't seen this linking error on any of the machines where I've installed it (which are all linux, not osx).

I suspect that @brhillman's issue is different from @tangq's.  Regarding @tangq's issue, it may be that there's some issue with the NCO build for OSX or a conflict with your existing environment.  I don't have a Mac of my own so I'm not in a position to investigate.  But the right place to pursue that issue is probably: https://github.com/conda-forge/nco-feedstock/

@brhillman, are you able to create an environment with just NCO on your machine?
```
conda create -n test_nco -c conda-forge python=2.7 nco
```
By the way, it's a little safer to create the environment with all packages listed than to do `conda create` followed by `conda install`.  The reason for this is that `conda install` can do different things depending on the order you add packages whereas `conda create` should always do the same thing.  But that's an aside and not related to the issue here.

If you're able to do that, there's a greater chance the issue is with e3sm-unified and I would recommend you build your own environment instead with just the packages you know you need and see if the issue happens there.  If I can figure out how to reproduce the issue, I'll be happy to debug it but I haven't been able to do so so far.

**Comment by tangq** [comment]
@xylar , on your command, you specified python2.7. I used python3.7 Miniconda. I will try the python2.7 Miniconda to verify if python version is the cause of this issue.

The Mac has just updated its system. It is possible that the OSX is too new for the NCO build.

**Comment by xylar** [comment]
@tangq, it shouldn't matter.  e3sm-unified only supports python 2.7 (and nco doesn't care about python) so whichever miniconda you use, you'll get python 2.7 in e3sm-unified.

**Comment by xylar** [comment]
On my own machine, I can install e3sm-unified:
```
conda create --name test_e3sm_unified_py2.7 -c conda-forge -c e3sm -c cdat python=2.7 e3sm-unified mesalib
```
I see a warning but I've never seen any errors result from it:
```
$ ncks --version
ncks: Relink `/home/xylar/miniconda3/envs/test_e3sm_unified_py2.7/bin/../lib/./libgfortran.so.3' with `/lib/x86_64-linux-gnu/librt.so.1' for IFUNC symbol `clock_gettime'
NCO netCDF Operators version 4.7.5 built by nobody on a2548b2bf3e3 at Jul 26 2018 00:17:37
ncks version 4.7.5
```
Just for completeness, here's the result of the command @czender requested.
```
$ ncremap --config
ncremap, the NCO regridder and map- and grid-generator, version 4.7.5
Copyright (C) 2016--2018 Charlie Zender
This program is part of NCO, the netCDF Operators
NCO is free software and comes with a BIG FAT KISS and ABSOLUTELY NO WARRANTY
You may redistribute and/or modify NCO under the terms of the
GNU General Public License (GPL) Version 3 with exceptions described in the LICENSE file
GPL: http://www.gnu.org/copyleft/gpl.html
LICENSE: https://github.com/nco/nco/tree/master/LICENSE
Config: ncremap running from directory /home/xylar/miniconda3/envs/test_e3sm_unified_py2.7/bin
Config: Calling NCO binaries in directory /home/xylar/miniconda3/envs/test_e3sm_unified_py2.7/bin
Config: Binaries linked to netCDF library version for
4.6.1
Config: No hardcoded path/module overrides
Config: ESMF weight-generation command ESMF_RegridWeightGen found as /home/xylar/miniconda3/envs/test_e3sm_unified_py2.7/bin/ESMF_RegridWeightGen
Config: Tempest weight-generation command GenerateOfflineMap not found
```

**Comment by tangq** [comment]
@xylar, I should clarify that I installed NCO on its own (conda install nco), not with e3sm-unified. Will it make a difference in terms of which python version is default?

**Comment by xylar** [comment]
If I had to guess, I think @brhillman's issue may come from a system library that's getting loaded through `LD_LIBRARY_PATH` and overriding python.  (conda environments don't play well with `LD_LIBRARY_PATH`.)  @brhillman, could you post (or email me if you prefer) the output from `env`?

**Comment by xylar** [comment]
@tangq, you don't need to install python at all if you're installing NCO on its own. Which version you install shouldn't make any difference.  I think your issue is something else but I'm not a Mac guy so I really won't be much help there, I'm afraid.

**Comment by tangq** [comment]
I followed the NCO documentation (http://nco.sourceforge.net/) to install it via Anaconda. That's why python is mentioned here. There are other ways listed on that page for Mac installation. I will try them. Thank you, @xylar .

**Comment by czender** [comment]
Thanks for helping, Xylar. Two reports of a link error in a short time made me think there had been a conda update that broke new installs, but your testing probably would have caught that. The dynamic linking error could by caused by `LD_LIBRARY_PATH` confusion, that's where I'd recommend looking too.

**Comment by xylar** [comment]
I'm going to leave this open for now but, @brhillman and @tangq, if you find a working solution on your respective machines, please comment here and close the issue.

**Comment by brhillman** [comment]
@xylar sorry I meant to get to this yesterday and ran out of time. I will investigate a little more today. I ended up bailing on using e3sm-unified and setup my own environment to solve my immediate problem (yes I can get NCO working by itself). I'm going to try setting up a fresh e3sm-unified environment to see if I can reproduce this issue and then report back.

**Comment by brhillman** [comment]
@xylar on my Mac I am trying the following command, copied from yours above:
```
conda create --name e3sm-unified -c conda-forge -c e3sm -c cdat python=2.7 e3sm-unified mesalib
```
and getting the following error:
```
bash-3.2$ conda create --name e3sm-unified -c conda-forge -c e3sm -c cdat python=2.7 e3sm-unified mesalib
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - e3sm-unified

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/e3sm/osx-64
  - https://conda.anaconda.org/e3sm/noarch
  - https://conda.anaconda.org/cdat/osx-64
  - https://conda.anaconda.org/cdat/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
```
This is with a local Anaconda install. Oddly, this same command succeeds on the Linux cluster I am using (on which I have installed a local Miniconda), and `ncks` seems to work without issue there:
```
(e3sm-unified) [bhillma@chama-login2 ~]$ ncks --version
NCO netCDF Operators version 4.7.5 built by nobody on a2548b2bf3e3 at Jul 26 2018 00:17:37
ncks version 4.7.5
```

**Comment by xylar** [comment]
So a lot of e3sm-unified packages aren't built for OSX so I think you'll have not luck there.  For now, your only option is to build your own environment with a subset of packages that work on the mac.

**Comment by brhillman** [comment]
Yeah that’s no problem. I think I’ll close this issue, because specifying the packages on the create env line seemed to fix my library link error. You might want to add this to the README at the top level of the repo, that was a useful hint I think.

**Comment by xylar** [comment]
Thanks @brhillman.  I'm happy to look into it further if you have any luck tracking down the linking issue, perhaps to interactions between some specific packages.  I know how hard that can be, though, so probably not worth your time if you have another solution.

I noted the lack of support for OSX and Windows near the top of the README.md just now.  Thanks for the suggestion.

**Comment by brhillman** [comment]
I’d also consider adding a note in the README about installing the via the conda create command (as you suggested in this thread) as opposed to conda install (as the the README current suggests). This seems to be more robust, and I would not have thought of that had you not suggested it here in this thread.

**Comment by xylar** [comment]
Ah, thanks for that.  The README.md is as bit out of date so that's a very good point.

**Comment by czender** [comment]
@brhillman does a simple NCO install like this
`conda install -c conda-forge nco 
` 
always work for you? on both Linux and MacOS? Or should I change the standalone NCO install recommendation to something more complex like
`conda create -n nco -c conda-forge python=2.7 nco
`
Thoughts?

**Comment by xylar** [comment]
@czender, the issue with `conda create` vs. `conda install` is basically to do with getting the expected versions of packages.  `conda create` is considered "best practices" but `conda install` should work just fine in nearly all cases.

It's also not considered a good practice to install into the `base` environment so that's why creating a new environment is encouraged.  Which you want to suggest to NCO users is entirely up to you.  I think it probably matters more and makes more sense for `e3sm-unified`, where it kind of defines a whole environment, not just one package in a larger environment.

**Comment by brhillman** [comment]
For what it's worth, I've never really had a problem with installing just NCO, I think the problem here was a bunch of other dependencies being brought in for e3sm-unified (and more than likely some user error on my part).

**Comment by czender** [comment]
Thanks, both of you. I'll leave the standalone NCO instructions as is for simplicity. It's good to know that is an escape hatch for more complex environments.

**Comment by tangq** [comment]
@czender , I suspect the issue I had for the standalone NCO installation is caused by the recent OS upgrade. However, I don't have an older MAC system to test on right now. I will report back if I have updates.

It is also good to know it's better to use `conda create`. Thanks, @xylar .
