### ISSUE TITLE
python 3.7 version of e3sm-unified

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm-unified#40]
Packages that support python 3.7:
- [x] cdat_info
- [x] cdms2
- [x] cdtime
- [x] cdutil
- [x] genutil
- [x] vtk-cdat
- [x] dv3d
- [x] vcs
- [x] vcsaddons
- [x] output_viewer
- [ ] e3sm_diags ==1.6.1
- [x] xarray
- [x] dask
- [x] nco
- [x] lxml
- [x] sympy
- [x] pyproj
- [x] pytest
- [x] shapely
- [x] cartopy
- [x] progressbar2
- [x] pillow
- [x] numpy >1.13
- [x] scipy
- [x] matplotlib
- [x] basemap
- [x] blas
- [x] jupyter
- [x] nb_conda
- [x] ipython
- [x] plotly
- [x] bottleneck
- [x] hdf5 ==1.10.3
- [x] netcdf4 ==1.4.2
- [x] evtk ==1.1.1
- [x] f90nml
- [x] globus-cli
- [x] globus-sdk
- [x] mpas_analysis ==1.2
- [ ] processflow
- [x] tabulate
- [x] cmocean
- [x] gsw
- [x] libnetcdf ==4.6.1
- [x] livvkit ==2.1.6
- [x] pyflann
- [x] scikit-image
- [x] shapely
- [ ] zstash ==0.2
- [x] ilamb ==2.4 [NEW]

The ones in bold are nearly there.

**Comment by xylar** [comment]
@jhkennedy, here's what we're up against, I'm afraid.  A lot of CDAT packages (those from the CDAT channel) aren't built with python 3.7 yet.  I think both `processflow` and `zstash` are strictly python 2.7 right now.

**Comment by rljacob** [comment]
@jgfouca didn't CIME use six.py to help support both python 2 and python 3?   Maybe that could help here.

**Comment by xylar** [comment]
@rljacob, thanks for the tip.  I think we have a pretty good handle on the process for making packages work with both.  @jhkennedy and I have both done this with LIVVKit and MPAS-Analysis, respectively.  I think @zshaheen and @chengzhuzhang have also done this with e3sm_diags.

The remaining work falls into two categories:
* A lot of CDAT packages (on the `cdat` channel) were built with python 3.6 but not 3.7.  With some help from @doutriaux1 or someone else on the CDAT team, this shouldn't be too hard to address
* `processflow` and `zstash` were written in python 2.7.  It's just a matter of @sterlingbaldwin and @zshaheen putting in the time to make them python-3 compatible, which is partly a question of priorities.  @jhkennedy and I are happy to help with that (as I think everyone involved knows).

**Comment by xylar** [comment]
As a fallback, all of the packages we need from the `cdat` channel do support python 3.6.  So if we get to a point where `processflow` and `zstash` are ready to go but `cdat` stuff isn't, we could do the first py3 version with 3.6.

**Comment by xylar** [comment]
It sounds like the various `cdat` packages will have a v8.1 release early next week, including python 3.7 support!  So that will take care of most of this.

**Comment by rljacob** [comment]
Q:  what does it mean to "support" python 3.6 vs. 3.7?   Are python minor versions so different that code is not forward portable?  Like going from 2 to 3?

**Comment by jhkennedy** [comment]
@rljacob in the conda context, it means there is a compatible build for that specific version of python. Fore example, `e3sm_nex` has a build matrix that includes py27, py36, win, osx, and linux, which you can see reflected in the file names here: https://anaconda.org/cdat/e3sm_nex/files

So supporting python 3.7 just requires someone to build a 3.7 version (or building a noarch package that works on *any* python, if possible). 

The major benefit of conda-forge is that the build matrix is handled automatically by CI tools, so if it's possible to get a package on conda-forge, that should be what's done. 

(@xylar I think that mostly covers it, did I miss anything? )

**Comment by jhkennedy** [comment]
And python minor versions should be backwards compatible, so if it works in 3.x it should work in 3.x+1. 

See [PEP 387](https://www.python.org/dev/peps/pep-0387/)

**Comment by xylar** [comment]
Thanks @jhkennedy, that covers it and I was in the process of writing essentially the same thing.

As @jhkennedy said, it's not necessarily about changing the code (I didn't have to do anything in MPAS-Analysis to support 3.6 and 3.7 once I got set up for python 3.5) but each package has to either be specifically built for each python major and minor version or it has to say that it works with all supported versions (on conda-forge, this is currently 2.7, 3.6, 3.7) without any differences in build.
