### ISSUE TITLE
Mac OSX build of e3sm-unified

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm-unified#41]
I've had several recent requests for (or, more accurately some confusion about) an OSX version of e3sm-unified.  All (or at least nearly all) conda-forge packages should support it.  I think many CDAT as well.  I don't think any (or not many) of the e3sm channel packages do.

Packages that support OSX:
- [x] cdat_info ==8.0
- [x] cdms2 ==3.1.2
- [x] cdtime ==3.1.2
- [x] cdutil ==8.0
- [x] genutil ==8.1
- [x] vtk-cdat ==8.0.1.8.0
- [x] dv3d ==8.0
- [x] vcs ==8.0
- [x] vcsaddons ==8.0
- [x] output_viewer ==1.2.5
- [x] e3sm_diags ==1.6.0
- [x] xarray ==0.11.3
- [x] dask ==1.1.1
- [x] nco ==4.7.9
- [x] lxml
- [x] sympy
- [x] pyproj
- [x] pytest
- [x] shapely
- [x] cartopy
- [x] progressbar2
- [x] pillow
- [x] numpy >1.13
- [x] scipy
- [x] matplotlib
- [x] basemap
- [x] blas
- [x] jupyter
- [x] nb_conda
- [x] ipython
- [x] plotly
- [x] bottleneck
- [x] hdf5 ==1.10.3
- [x] netcdf4 ==1.4.2
- [x] evtk ==1.1.1
- [x] f90nml
- [x] globus-cli
- [x] globus-sdk
- [x] mpas_analysis ==1.2
- [ ] processflow ==2.1.1
- [x] tabulate
- [x] cmocean
- [x] gsw
- [x] libnetcdf ==4.6.1
- [x] livvkit ==2.1.6
- [x] pyflann
- [x] scikit-image
- [x] shapely
- [ ] zstash ==0.3
- [x] ilamb >=2.3.1 [NEW]

**Comment by xylar** [comment]
With some help from @jhkennedy, I could probably move the 2 globus packages to conda-forge and they would get built properly.

@sterlingbaldwin, how hard would it be to make an OSX build of processflow (and would that even make sense to do)?

**Comment by jhkennedy** [comment]
I'm happy to help with the globus packages

**Comment by xylar** [comment]
The current packages [here](https://github.com/E3SM-Project/e3sm-unified/blob/master/globus-cli/meta.yaml) and [here](https://github.com/E3SM-Project/e3sm-unified/blob/master/globus-sdk/meta.yaml) were created using the automated tools from the pypi projects [here](https://pypi.org/project/globus-cli/) and [here](https://pypi.org/project/globus-sdk/)

My guess is that there are tools from creating conda-forge recipes from pypi (though I've never made a conda-forge recipe, to be honest) so it might be easier to start over from pypi than to use my recipes. @jhkennedy, what do you think?

**Comment by xylar** [comment]
Based on the FAQ, they suggest using either `skeleton` and then editing the `meta.yaml` or just creating the `meta.yaml` from scratch, so I guess my existing recipes will be the starting point.  Looks easier than I feared.

**Comment by jhkennedy** [comment]
Both those recipes are pretty straight forward, so I don't think they'll need much modification. They do like you to minimize the jinja2 template variables, so I suspect they'll ask you to not include these as variables:

```
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2efb291ea03809e30d7e357955fbf777e6c2485cb61997656a314bf7695169f5" %}
```

The basic process for conda-forge is:
* to fork `https://github.com/conda-forge/staged-recipes`
* add the recipe for `PACKAGE` under the `recipes/PACKAGE` directory
* open a PR to `conda-forge/staged-recipes:master`

That will kick off a bunch of different CI jobs that will lint the recipe, run the build matrix, and check the PR. Once that passes, someone on the conda-forge team will check over the recipe, and if it all looks good, will merge the PR. 

Merging the PR will cause a `conda-forge/PACKAGE-feedstock` repository to be created, and add the listed recipe maintainers as team members for that repo. It's here that future package updates will happen or changes to the recipe. 

For example, you can see my ILAMB PR here: https://github.com/conda-forge/staged-recipes/pull/7819
And the json_tricks feedstock I maintain here (most recently updated): https://github.com/conda-forge/json_tricks-feedstock

The docs for conda-forge are very confusing, so you end up having to piece together the puzzle from both: 
* the conda-forge docs: https://conda-forge.org/docs/meta.html
* the conda-build docs: https://docs.conda.io/projects/conda-build/en/latest/index.html

If you'd like, I could get the initial conda-recipes PR going and list you as a maintainer, or if you want to go through the process yourself, you're welcome to also name me as a maintainer and I'll help when needed.

**Comment by sterlingbaldwin** [comment]
Is it possible to do an OSX build without the processflow/globus packages? Ive had a couple users ask for a serial version, but for the time being processflow expects to be running on a cluster and submits all its jobs to slurm/pbs.

**Comment by xylar** [comment]
> Is it possible to do an OSX build without the processflow/globus packages? 

Yes, it would be possible.  I think it's worth migrating `globus` to `conda-forge` and seeing if we can support OSX.  But we could drop `processflow` from the OSX version.

**Comment by xylar** [comment]
Thanks for the instructions, @jhkennedy

**Comment by sterlingbaldwin** [comment]
At the last E3SM meeting there were a couple users that asked for a serial version they could use to run small jobs on their workstations, so this is something I want to support but I dont want to hold you back for the time being.

**Comment by rljacob** [comment]
If processflow is in the MacOSX build, can we just tell people "don't use this"?  The rest of the packages will still work right?

**Comment by zshaheen** [comment]
Yeah, `zstash`, which depends on `hsi` isn't going to work on macOS as well. Since `hsi` is closed sourced (or something like that) I don't think we'll get a macOS version.

**Comment by xylar** [comment]
Okay, that's fine.  `zstash` is a no, `processflow` is a probably not for OSX.  We can certainly do that.  I think it's better to just not include the package in the OSX build rather than including it but telling people not to use it.  That's not a problem.
