### ISSUE TITLE
Enable better CI

### ISSUE THREAD

**Issue by rpwagner** [E3SM-Project/e3sm-unified#58]
@xylar Once the CI build is fixed, we need to work out the chicken and egg problem with CI. Currently, testing the `e3sm-unified` Conda metapackage depends on Conda being updated. For actual CI, we should be doing `conda create` using the metapackage definition in the repo or pull request.

Nightly builds do basically what we want by checking that changes in dependencies aren't breaking things. But PRs aren't testing that changes to the metapackage definition don't break anything.

A fast compromise is to just unpin the `e3sm-unified` version in the container definition file. That would make the nightly build do the check after the metapackage is updated. It will need to be updated for change to Python 3 anyways.

```
    conda create -n e3sm-unified-nox -c conda-forge -c e3sm -c cdat/label/v81 python=2.7 e3sm-unified=1.2.6 mesalib
```

**Comment by xylar** [comment]
@rpwagner, I agree that the fast compromise of using the latest version for nightly builds would be the starting point.

Once that is done, we would need to switch to downloading the source from the PR, building the package with conda-build, and installing it from "local" for CI on PRs and merges.  Nightly CI should still use the latest uploaded package.

**Comment by rpwagner** [comment]
@xylar, OK. I'll do a PR updating the definition file to ensure it's building now, before #55 is merged.

**Comment by xylar** [comment]
It's working fine for me to first upload packages and then update CI to use the new packages, so I'm going to close this.
