### ISSUE TITLE
Change from acme to e3sm on NERSC

### ISSUE THREAD

**Issue by eroesler** [E3SM-Project/e3sm-unified#72]
In 
/global/project/projectdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh

can you please change 

source /global/cfs/cdirs/acme/software/anaconda_envs/base/etc/profile.d/conda.sh

to 

source /global/cfs/cdirs/e3sm/software/anaconda_envs/base/etc/profile.d/conda.sh

**Comment by xylar** [comment]
@eroesler, thanks for bringing this to my attention.  This will require rebuilding the environments rather than just modifying the link because they include hard-coded paths.  I'll work on this now and update the documentation once it's done.

**Comment by xylar** [comment]
@eroesler, thank you again.  The environments have now been replaced with new ones with the correct path.  Please email me or open a new issue if you have any trouble.
