### ISSUE TITLE
MPI_Init error running ilamb on LCRC

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm-unified#95]
I'm trying to setup an ilamb run on LCRC. But a test run resulted an MPI_init error as follows:

`ilamb-run --config /home/ac.zhang40/ILAMB/src/ILAMB/data/cmip.cfg --model_root /lcrc/group/e3sm/ac.zhang40/ilamb_test_data/ --regions global bona`

```
--------------------------------------------------------------------------
PMI2_Init failed to intialize.  Return code: 14
--------------------------------------------------------------------------
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[chr-0369:1658739] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Comment by minxu74** [comment]
@chengzhuzhang could you try the following command to see if it works?
`
srun -n 1 ilamb-run --config /home/ac.zhang40/ILAMB/src/ILAMB/data/cmip.cfg --model_root /lcrc/group/e3sm/ac.zhang40/ilamb_test_data/ --regions global bona
`

If it does not work, we may have to use system mpi4py, instead of the one installed by conda. 

I do not have an account on LCRC machines, otherwise, I can look into it and try the above command.

**Comment by xylar** [comment]
Thanks @minxu74.  Using system `mpi4py` might be a possibility.

**Comment by chengzhuzhang** [comment]
@xylar and @minxu74 Thank you for taking a look! When I try it today, it worked. Must be some one time glitch yesterday.

**Comment by xylar** [comment]
Okay, well that's a little disconcerting but hopefully it won't happen again.  If it does, let's try to find out more.  Using system `mpi4py`, if there is such a thing, might be an option.
